### PR TITLE
Add Cocoapods support

### LINKED ISSUE #4: Support cocoaPods?

### PR DESCRIPTION
**Pull request by StevenMagdy**
Fixes #4 

@marksands Still need to push the spec through `pod trunk push BetterCodable.podspec`, but I will leave that to you.

### CODE REVIEW

**Comment by marksands** [comment]
🎉  Sorry this took me so long to get to. I'll try and get the spec up this weekend. I don't have ruby installed on my machine so I'll get to go through that fun dance! 😄

**Comment by StevenMagdy** [comment]
Hey @marksands, when you will be able to push the spec? I need it for a current project 😄 
I can push it for you if you don't want to.

**Comment by marksands** [comment]
@StevenMagdy Very sorry! I just pushed up 0.1.0 to cocoapods so you should be set. Let me know if that doesn't work for you!!

**Comment by StevenMagdy** [comment]
@marksands Thank you, pulled successfully.

**Pull request merged**
