### PR TITLE
Implement general DefaultValue PropertyWrapper

### PR DESCRIPTION
**Pull request by serjooo**
This PR introduces `DefaultValue` to most Basic data types

### CODE REVIEW

**Comment by marksands** [comment]
I like where you're head's at! I think one needs to exercise caution when making a catch-all `@Defaultable` wrapper that can make arbitrary decisions based upon anyones needs. Defaulting to always false or always zero is probably not what _everyone_ wants.

If you're looking for a really solid Defaultable idea that allows maximum flexibility you should take a look at [Ian's playground](https://github.com/IanKeen/Defaultable). His implementation allows you to make custom providers like this:

```swift
// example default value provider
struct FortyTwo<N: Numeric>: DefaultValue {
    static var `default`: N { return 42 }
}

// example model
struct Model: Codable, Hashable {
    @Defaultable<Bool, True> var bool: Bool
    @Defaultable<Float, Zero<Float>> var float: Float
    @Defaultable<Int, FortyTwo<Int>> var int: Int
    @Defaultable<String, EmptyString> var string: String
}
```

**Comment by serjooo** [comment]
Thank you for the quick reply and thank you for linking me to Ian's playground!

> I think one needs to exercise caution when making a catch-all @Defaultable wrapper that can make arbitrary decisions based upon anyones needs. Defaulting to always false or always zero is probably not what everyone wants.

I completely agree with this one! I tried to implement a way to pass `DefaultValues` with the `PropertyWrapper`; however, couldn't come up with a good way to do it. I then had the thought if it's really worth it. I thought most of the time the `DefaultValue` that one would like to default is the `zero` or `false` or `EmptyString` as when values are nil and you have a non-optional based APIs on the `View` side you will most probably default that `Model`'s property to those defaults. Even though, I was hesitant defaulting `Date` to the current `Date` because it is never the case.

 I think Ian's approach is really nice, even though maybe it could get really inconvenient/verbose to implement a `struct` per `DefaultValue`. It is still a really good solution. Were you planning on implementing it in `BetterCodable`?

**Comment by marksands** [comment]
Not at the moment. I’ve already _borrowed_ a lot of Ian’s ideas as it is! Future evolutions of Swift might allow for more elegant solutions to the defaultable scenario, so I’m kind of waiting for that. I may toy around with a different spin on it, but for now I’d suggest folks check out Ian’s solution! 😄

**Comment by serjooo** [comment]
Alright deal sounds good. I'm going to close the PR for the better future solution. Any specific evolution you are waiting for which is maybe a WIP? I will definitely implement Ian's solution on my Fork it will definitely come in handy! Again Thank you for pointing me to it!

**Comment by marksands** [comment]
@serjooo There's no harm in me copying over the `DateValueCodableStrategy` idea to the Default types. I just pushed an update that extracts a [DefaultCodable](https://github.com/marksands/BetterCodable/blob/6e6c45476f978656c8880ce024f20e7a927af755/Sources/BetterCodable/DefaultCodable.swift) that might get you what you want. The only caveat is that it's not a truly generic `Defaultable` for all types, right now this is specific for `Codable` types.

**Comment by marksands** [comment]
So if you wanted your own `@DefaultEmptyString` wrapper you could easily accomplish this:

```
struct DefaultEmptyStringStrategy: DefaultCodableStrategy {
    static var defaultValue: String { return "" }
}
typealias DefaultEmptyString = DefaultCodable<DefaultEmptyStringStrategy>
```

Or a `@DefaultNumericZero` as well:

```
struct DefaultNumericZeroStrategy<N: Numeric & Codable>: DefaultCodableStrategy {
    static var defaultValue: N { return 0 }
}
typealias DefaultNumericZero<N> = DefaultCodable<DefaultNumericZeroStrategy<N>> where N: Numeric & Codable
```

**Comment by serjooo** [comment]
@marksands Looks really good! 

> The only caveat is that it's not a truly generic Defaultable for all types, right now this is specific for Codable types.

I don't think it's a caveat as while using `BetterCodable` we would only be using these `PropertyWrapper`s for giving default value for `Codable` types, so it is perfectly fine. Great work and thank you for adding it!

**Pull request closed without merging**
