### PR TITLE
renamed RawValue of DefaultCodableStrategy to DefaultValue

### PR DESCRIPTION
**Pull request by oliverkrakora**
this PR addresses the issue #32

### CODE REVIEW

**Comment by marksands** [comment]
Thank you! 🚀 Sorry it too me way too long to get to this.

**Comment by oliverkrakora** [comment]
No worries, thank you! 🙂

**Comment by ivanglushko** [comment]
Guys it's not in the pod version for now. Really bugs me :D

**Comment by ivanglushko** [comment]
For now I use SPM

**Pull request merged**
